from __future__ import unicode_literals
import frappe
from frappe import _
from erpnext.setup.utils import insert_record


def after_install():
    forms = [
        dict(
            doctype='CETI Form',
            title='Restaurant Room',
            route='restaurant-room',
            doc_type='Restaurant Object',
            module='Restaurant Management',
            is_standar=1,
        ),
        dict(
            doctype='CETI Form',
            title='Restaurant Table',
            route='restaurant-table',
            doc_type='Restaurant Object',
            module='Restaurant Management',
            is_standar=1,
        ),
        dict(
            doctype='CETI Form',
            title='Restaurant Production Center',
            route='restaurant-production-center',
            doc_type='Restaurant Object',
            module='Restaurant Management',
            is_standar=1,
        ),
        dict(
            doctype='CETI Form',
            title='Restaurant Order',
            route='restaurant-order',
            doc_type='Table Order',
            module='Restaurant Management',
            is_standar=1,
        ),
        dict(
            doctype='CETI Form',
            title='Order Item Note',
            route='order-item-note',
            doc_type='Order Entry Item',
            module='Restaurant Management',
            is_standar=1,
        ),
        dict(
            doctype='CETI Form',
            title='Customer Edit',
            route='customer-edit',
            doc_type='Customer',
            module='Restaurant Management',
            is_standar=1,
        ),
        dict(
            doctype='CETI Form',
            title='Payment Order',
            route='payment-order',
            doc_type='Table Order',
            module='Restaurant Management',
            is_standar=1,
        ),
    ]

    for form in forms:
        if frappe.get_value("CETI Form", {
            "route": form["route"]
        }) is None:
            insert_record([form])

    docs = ["restaurant-room", "restaurant-table", "restaurant-production-center",
            "restaurant-order", "order-item-note", "customer-edit", "payment-order"]

    fields = [
        {"name": "\"10f8717de4\"", "creation": "2020-07-26 02:20:22.059834", "modified": "2020-07-26 02:20:22.059834",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0,
         "parent": "restaurant-production-center", "parentfield": "ceti_form_fields", "parenttype": "CETI Form",
         "idx": 8, "fieldname": "section_break_10", "fieldtype": "Section Break", "label": None,
         "allow_read_on_all_link_options": 0, "reqd": 0, "depends_on": None, "read_only": 0, "show_in_filter": 0,
         "hidden": 0, "options": None, "max_length": 0, "max_value": 0, "description": None, "default": None},
        {"name": "\"11556cdd28\"", "creation": "2020-07-26 02:20:22.006061", "modified": "2020-07-26 02:20:22.006061",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0, "parent": "restaurant-table",
         "parentfield": "ceti_form_fields", "parenttype": "CETI Form", "idx": 6, "fieldname": "column_break_4",
         "fieldtype": "Column Break", "label": None, "allow_read_on_all_link_options": 0, "reqd": 0, "depends_on": None,
         "read_only": 0, "show_in_filter": 0, "hidden": 0, "options": None, "max_length": 0, "max_value": 0,
         "description": None, "default": None},
        {"name": "\"140da7de0e\"", "creation": "2020-07-26 02:20:22.006061", "modified": "2020-07-26 02:20:22.006061",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0, "parent": "restaurant-table",
         "parentfield": "ceti_form_fields", "parenttype": "CETI Form", "idx": 4, "fieldname": "section_break_2",
         "fieldtype": "Section Break", "label": None, "allow_read_on_all_link_options": 0, "reqd": 0,
         "depends_on": None, "read_only": 0, "show_in_filter": 0, "hidden": 0, "options": None, "max_length": 0,
         "max_value": 0, "description": None, "default": None},
        {"name": "\"14444cfc7b\"", "creation": "2020-07-26 02:20:22.059834", "modified": "2020-07-26 02:20:22.059834",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0,
         "parent": "restaurant-production-center", "parentfield": "ceti_form_fields", "parenttype": "CETI Form",
         "idx": 5, "fieldname": "description", "fieldtype": "Data", "label": "Description",
         "allow_read_on_all_link_options": 0, "reqd": 0, "depends_on": None, "read_only": 0, "show_in_filter": 0,
         "hidden": 0, "options": None, "max_length": 0, "max_value": 0, "description": None, "default": None},
        {"name": "\"154459dd75\"", "creation": "2020-07-26 02:20:22.006061", "modified": "2020-07-26 02:20:22.006061",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0, "parent": "restaurant-table",
         "parentfield": "ceti_form_fields", "parenttype": "CETI Form", "idx": 2, "fieldname": "column_break_2",
         "fieldtype": "Column Break", "label": None, "allow_read_on_all_link_options": 0, "reqd": 0, "depends_on": None,
         "read_only": 0, "show_in_filter": 0, "hidden": 0, "options": None, "max_length": 0, "max_value": 0,
         "description": None, "default": None},
        {"name": "\"1f208950c5\"", "creation": "2020-07-26 02:20:21.576334", "modified": "2020-07-26 02:20:21.576334",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0, "parent": "payment-order",
         "parentfield": "ceti_form_fields", "parenttype": "CETI Form", "idx": 4, "fieldname": None,
         "fieldtype": "Section Break", "label": None, "allow_read_on_all_link_options": 0, "reqd": 0,
         "depends_on": None, "read_only": 0, "show_in_filter": 0, "hidden": 0, "options": None, "max_length": 0,
         "max_value": 0, "description": None, "default": None},
        {"name": "\"2008102660\"", "creation": "2020-07-26 02:20:21.865901", "modified": "2020-07-26 02:20:21.865901",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0, "parent": "customer-edit",
         "parentfield": "ceti_form_fields", "parenttype": "CETI Form", "idx": 4, "fieldname": "salutation",
         "fieldtype": "Link", "label": "Salutation", "allow_read_on_all_link_options": 0, "reqd": 0, "depends_on": None,
         "read_only": 0, "show_in_filter": 0, "hidden": 0, "options": "Salutation", "max_length": 0, "max_value": 0,
         "description": None, "default": None},
        {"name": "\"29edd6e874\"", "creation": "2020-07-26 02:20:22.006061", "modified": "2020-07-26 02:20:22.006061",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0, "parent": "restaurant-table",
         "parentfield": "ceti_form_fields", "parenttype": "CETI Form", "idx": 11, "fieldname": "color",
         "fieldtype": "Color", "label": "Color", "allow_read_on_all_link_options": 0, "reqd": 0, "depends_on": None,
         "read_only": 0, "show_in_filter": 0, "hidden": 0, "options": None, "max_length": 0, "max_value": 0,
         "description": None, "default": None},
        {"name": "\"2a65925790\"", "creation": "2020-07-26 02:20:21.865901", "modified": "2020-07-26 02:20:21.865901",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0, "parent": "customer-edit",
         "parentfield": "ceti_form_fields", "parenttype": "CETI Form", "idx": 5, "fieldname": "is_frozen",
         "fieldtype": "Check", "label": "Is Frozen", "allow_read_on_all_link_options": 0, "reqd": 0, "depends_on": None,
         "read_only": 0, "show_in_filter": 0, "hidden": 0, "options": None, "max_length": 0, "max_value": 0,
         "description": None, "default": "0"},
        {"name": "\"2b6bc5e29b\"", "creation": "2020-07-26 02:20:21.576334", "modified": "2020-07-26 02:20:21.576334",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0, "parent": "payment-order",
         "parentfield": "ceti_form_fields", "parenttype": "CETI Form", "idx": 8, "fieldname": None,
         "fieldtype": "Section Break", "label": None, "allow_read_on_all_link_options": 0, "reqd": 0,
         "depends_on": None, "read_only": 0, "show_in_filter": 0, "hidden": 0, "options": None, "max_length": 0,
         "max_value": 0, "description": None, "default": None},
        {"name": "\"2b7f19f306\"", "creation": "2020-07-26 02:20:21.914657", "modified": "2020-07-26 02:20:21.914657",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0, "parent": "restaurant-room",
         "parentfield": "ceti_form_fields", "parenttype": "CETI Form", "idx": 1, "fieldname": "restaurant",
         "fieldtype": "Link", "label": "Restaurant", "allow_read_on_all_link_options": 0, "reqd": 0, "depends_on": None,
         "read_only": 0, "show_in_filter": 0, "hidden": 0, "options": "Restaurant", "max_length": 0, "max_value": 0,
         "description": None, "default": None},
        {"name": "\"34d2e9818f\"", "creation": "2020-07-26 02:20:22.006061", "modified": "2020-07-26 02:20:22.006061",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0, "parent": "restaurant-table",
         "parentfield": "ceti_form_fields", "parenttype": "CETI Form", "idx": 10, "fieldname": "column_break_8",
         "fieldtype": "Column Break", "label": None, "allow_read_on_all_link_options": 0, "reqd": 0, "depends_on": None,
         "read_only": 0, "show_in_filter": 0, "hidden": 0, "options": None, "max_length": 0, "max_value": 0,
         "description": None, "default": None},
        {"name": "\"3bd2015379\"", "creation": "2020-07-26 02:20:21.576334", "modified": "2020-07-26 02:20:21.576334",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0, "parent": "payment-order",
         "parentfield": "ceti_form_fields", "parenttype": "CETI Form", "idx": 7, "fieldname": None, "fieldtype": "HTML",
         "label": "Num Pad", "allow_read_on_all_link_options": 0, "reqd": 0, "depends_on": None, "read_only": 0,
         "show_in_filter": 0, "hidden": 0, "options": None, "max_length": 0, "max_value": 0, "description": None,
         "default": None},
        {"name": "\"3da6bca99f\"", "creation": "2020-07-26 02:20:21.576334", "modified": "2020-07-26 02:20:21.576334",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0, "parent": "payment-order",
         "parentfield": "ceti_form_fields", "parenttype": "CETI Form", "idx": 9, "fieldname": None,
         "fieldtype": "Currency", "label": "Total Payment", "allow_read_on_all_link_options": 0, "reqd": 0,
         "depends_on": None, "read_only": 1, "show_in_filter": 0, "hidden": 0, "options": None, "max_length": 0,
         "max_value": 0, "description": None, "default": None},
        {"name": "\"3f381ba796\"", "creation": "2020-07-26 02:20:21.962812", "modified": "2020-07-26 02:20:21.962812",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0, "parent": "order-item-note",
         "parentfield": "ceti_form_fields", "parenttype": "CETI Form", "idx": 1, "fieldname": "notes",
         "fieldtype": "Text", "label": "Notes", "allow_read_on_all_link_options": 0, "reqd": 0, "depends_on": None,
         "read_only": 0, "show_in_filter": 0, "hidden": 0, "options": None, "max_length": 0, "max_value": 0,
         "description": None, "default": None},
        {"name": "\"47ec1b6f4b\"", "creation": "2020-07-26 02:20:21.865901", "modified": "2020-07-26 02:20:21.865901",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0, "parent": "customer-edit",
         "parentfield": "ceti_form_fields", "parenttype": "CETI Form", "idx": 2, "fieldname": "tax_id",
         "fieldtype": "Data", "label": "Tax ID", "allow_read_on_all_link_options": 0, "reqd": 0, "depends_on": None,
         "read_only": 0, "show_in_filter": 0, "hidden": 0, "options": None, "max_length": 0, "max_value": 0,
         "description": None, "default": None},
        {"name": "\"49efb44075\"", "creation": "2020-07-26 02:20:22.115430", "modified": "2020-07-26 02:20:22.115430",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0, "parent": "restaurant-order",
         "parentfield": "ceti_form_fields", "parenttype": "CETI Form", "idx": 3, "fieldname": "dinners",
         "fieldtype": "Int", "label": "Dinners", "allow_read_on_all_link_options": 0, "reqd": 0, "depends_on": None,
         "read_only": 0, "show_in_filter": 0, "hidden": 0, "options": None, "max_length": 0, "max_value": 0,
         "description": None, "default": None},
        {"name": "\"4ce3ef329b\"", "creation": "2020-07-26 02:20:21.576334", "modified": "2020-07-26 02:20:21.576334",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0, "parent": "payment-order",
         "parentfield": "ceti_form_fields", "parenttype": "CETI Form", "idx": 13, "fieldname": "amount",
         "fieldtype": "Currency", "label": "Amount", "allow_read_on_all_link_options": 0, "reqd": 1, "depends_on": None,
         "read_only": 1, "show_in_filter": 0, "hidden": 0, "options": None, "max_length": 0, "max_value": 0,
         "description": None, "default": None},
        {"name": "\"4d3700b543\"", "creation": "2020-07-26 02:20:21.576334", "modified": "2020-07-26 02:20:21.576334",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0, "parent": "payment-order",
         "parentfield": "ceti_form_fields", "parenttype": "CETI Form", "idx": 2, "fieldname": None,
         "fieldtype": "Column Break", "label": None, "allow_read_on_all_link_options": 0, "reqd": 0, "depends_on": None,
         "read_only": 0, "show_in_filter": 0, "hidden": 0, "options": None, "max_length": 0, "max_value": 0,
         "description": None, "default": None},
        {"name": "\"54ea575355\"", "creation": "2020-07-26 02:20:22.059834", "modified": "2020-07-26 02:20:22.059834",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0,
         "parent": "restaurant-production-center", "parentfield": "ceti_form_fields", "parenttype": "CETI Form",
         "idx": 10, "fieldname": "section_break_12", "fieldtype": "Section Break", "label": None,
         "allow_read_on_all_link_options": 0, "reqd": 0, "depends_on": None, "read_only": 0, "show_in_filter": 0,
         "hidden": 0, "options": None, "max_length": 0, "max_value": 0, "description": None, "default": None},
        {"name": "\"59dbe96de7\"", "creation": "2020-07-26 02:20:22.115430", "modified": "2020-07-26 02:20:22.115430",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0, "parent": "restaurant-order",
         "parentfield": "ceti_form_fields", "parenttype": "CETI Form", "idx": 2, "fieldname": None,
         "fieldtype": "Column Break", "label": None, "allow_read_on_all_link_options": 0, "reqd": 0, "depends_on": None,
         "read_only": 0, "show_in_filter": 0, "hidden": 0, "options": None, "max_length": 0, "max_value": 0,
         "description": None, "default": None},
        {"name": "\"5d8d9e374b\"", "creation": "2020-07-26 02:20:21.865901", "modified": "2020-07-26 02:20:21.865901",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0, "parent": "customer-edit",
         "parentfield": "ceti_form_fields", "parenttype": "CETI Form", "idx": 1, "fieldname": "customer_name",
         "fieldtype": "Data", "label": "Full Name", "allow_read_on_all_link_options": 0, "reqd": 1, "depends_on": None,
         "read_only": 0, "show_in_filter": 0, "hidden": 0, "options": None, "max_length": 0, "max_value": 0,
         "description": None, "default": None},
        {"name": "\"64d423e5ce\"", "creation": "2020-07-26 02:20:22.059834", "modified": "2020-07-26 02:20:22.059834",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0,
         "parent": "restaurant-production-center", "parentfield": "ceti_form_fields", "parenttype": "CETI Form",
         "idx": 6, "fieldname": "column_break_8", "fieldtype": "Column Break", "label": None,
         "allow_read_on_all_link_options": 0, "reqd": 0, "depends_on": None, "read_only": 0, "show_in_filter": 0,
         "hidden": 0, "options": None, "max_length": 0, "max_value": 0, "description": None, "default": None},
        {"name": "\"6ce99fe2bf\"", "creation": "2020-07-26 02:20:21.576334", "modified": "2020-07-26 02:20:21.576334",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0, "parent": "payment-order",
         "parentfield": "ceti_form_fields", "parenttype": "CETI Form", "idx": 11, "fieldname": None,
         "fieldtype": "Currency", "label": "Change Amount", "allow_read_on_all_link_options": 0, "reqd": 0,
         "depends_on": None, "read_only": 1, "show_in_filter": 0, "hidden": 0, "options": None, "max_length": 0,
         "max_value": 0, "description": None, "default": None},
        {"name": "\"7a953266bc\"", "creation": "2020-07-26 02:20:22.059834", "modified": "2020-07-26 02:20:22.059834",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0,
         "parent": "restaurant-production-center", "parentfield": "ceti_form_fields", "parenttype": "CETI Form",
         "idx": 1, "fieldname": "type", "fieldtype": "Select", "label": "Type", "allow_read_on_all_link_options": 0,
         "reqd": 1, "depends_on": None, "read_only": 0, "show_in_filter": 0, "hidden": 0,
         "options": "Room\nTable\nProduction Center\nTemporary Room\nDecorative", "max_length": 0, "max_value": 0,
         "description": None, "default": None},
        {"name": "\"7cde57d087\"", "creation": "2020-07-26 02:20:22.059834", "modified": "2020-07-26 02:20:22.059834",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0,
         "parent": "restaurant-production-center", "parentfield": "ceti_form_fields", "parenttype": "CETI Form",
         "idx": 3, "fieldname": "room", "fieldtype": "Link", "label": "Room", "allow_read_on_all_link_options": 0,
         "reqd": 0, "depends_on": None, "read_only": 0, "show_in_filter": 0, "hidden": 0,
         "options": "Restaurant Object", "max_length": 0, "max_value": 0, "description": None, "default": None},
        {"name": "\"8c663028bf\"", "creation": "2020-07-26 02:20:22.006061", "modified": "2020-07-26 02:20:22.006061",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0, "parent": "restaurant-table",
         "parentfield": "ceti_form_fields", "parenttype": "CETI Form", "idx": 8, "fieldname": "section_break_6",
         "fieldtype": "Section Break", "label": None, "allow_read_on_all_link_options": 0, "reqd": 0,
         "depends_on": None, "read_only": 0, "show_in_filter": 0, "hidden": 0, "options": None, "max_length": 0,
         "max_value": 0, "description": None, "default": None},
        {"name": "\"8db910a9df\"", "creation": "2020-07-26 02:20:22.006061", "modified": "2020-07-26 02:20:22.006061",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0, "parent": "restaurant-table",
         "parentfield": "ceti_form_fields", "parenttype": "CETI Form", "idx": 3, "fieldname": "room",
         "fieldtype": "Link", "label": "Room", "allow_read_on_all_link_options": 0, "reqd": 0, "depends_on": None,
         "read_only": 0, "show_in_filter": 0, "hidden": 0, "options": "Restaurant Object", "max_length": 0,
         "max_value": 0, "description": None, "default": None},
        {"name": "\"904b09fa0c\"", "creation": "2020-07-26 02:20:21.576334", "modified": "2020-07-26 02:20:21.576334",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0, "parent": "payment-order",
         "parentfield": "ceti_form_fields", "parenttype": "CETI Form", "idx": 3, "fieldname": None, "fieldtype": "HTML",
         "label": "Dinners Number", "allow_read_on_all_link_options": 0, "reqd": 1, "depends_on": None, "read_only": 0,
         "show_in_filter": 0, "hidden": 0, "options": None, "max_length": 0, "max_value": 0, "description": None,
         "default": None},
        {"name": "\"975f138388\"", "creation": "2020-07-26 02:20:21.576334", "modified": "2020-07-26 02:20:21.576334",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0, "parent": "payment-order",
         "parentfield": "ceti_form_fields", "parenttype": "CETI Form", "idx": 15, "fieldname": None,
         "fieldtype": "HTML", "label": "Payment Button", "allow_read_on_all_link_options": 0, "reqd": 0,
         "depends_on": None, "read_only": 0, "show_in_filter": 0, "hidden": 0, "options": None, "max_length": 0,
         "max_value": 0, "description": None, "default": None},
        {"name": "\"9904a6d2ca\"", "creation": "2020-07-26 02:20:22.059834", "modified": "2020-07-26 02:20:22.059834",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0,
         "parent": "restaurant-production-center", "parentfield": "ceti_form_fields", "parenttype": "CETI Form",
         "idx": 2, "fieldname": "column_break_2", "fieldtype": "Column Break", "label": None,
         "allow_read_on_all_link_options": 0, "reqd": 0, "depends_on": None, "read_only": 0, "show_in_filter": 0,
         "hidden": 0, "options": None, "max_length": 0, "max_value": 0, "description": None, "default": None},
        {"name": "\"9a8e228917\"", "creation": "2020-07-26 02:20:21.576334", "modified": "2020-07-26 02:20:21.576334",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0, "parent": "payment-order",
         "parentfield": "ceti_form_fields", "parenttype": "CETI Form", "idx": 6, "fieldname": None,
         "fieldtype": "Column Break", "label": None, "allow_read_on_all_link_options": 0, "reqd": 0, "depends_on": None,
         "read_only": 0, "show_in_filter": 0, "hidden": 0, "options": None, "max_length": 0, "max_value": 0,
         "description": None, "default": None},
        {"name": "\"9d99fc0d1b\"", "creation": "2020-07-26 02:20:22.006061", "modified": "2020-07-26 02:20:22.006061",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0, "parent": "restaurant-table",
         "parentfield": "ceti_form_fields", "parenttype": "CETI Form", "idx": 5, "fieldname": "no_of_seats",
         "fieldtype": "Int", "label": "No of Seats", "allow_read_on_all_link_options": 0, "reqd": 1, "depends_on": None,
         "read_only": 0, "show_in_filter": 0, "hidden": 0, "options": None, "max_length": 0, "max_value": 0,
         "description": None, "default": None},
        {"name": "\"a6690a925d\"", "creation": "2020-07-26 02:20:21.576334", "modified": "2020-07-26 02:20:21.576334",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0, "parent": "payment-order",
         "parentfield": "ceti_form_fields", "parenttype": "CETI Form", "idx": 1, "fieldname": "customer",
         "fieldtype": "Link", "label": "Customer", "allow_read_on_all_link_options": 0, "reqd": 1, "depends_on": None,
         "read_only": 0, "show_in_filter": 0, "hidden": 0, "options": "Customer", "max_length": 0, "max_value": 0,
         "description": None, "default": None},
        {"name": "\"a7f64072ed\"", "creation": "2020-07-26 02:20:21.576334", "modified": "2020-07-26 02:20:21.576334",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0, "parent": "payment-order",
         "parentfield": "ceti_form_fields", "parenttype": "CETI Form", "idx": 12, "fieldname": None,
         "fieldtype": "Section Break", "label": None, "allow_read_on_all_link_options": 0, "reqd": 0,
         "depends_on": None, "read_only": 0, "show_in_filter": 0, "hidden": 0, "options": None, "max_length": 0,
         "max_value": 0, "description": None, "default": None},
        {"name": "\"ab319ac10f\"", "creation": "2020-07-26 02:20:21.865901", "modified": "2020-07-26 02:20:21.865901",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0, "parent": "customer-edit",
         "parentfield": "ceti_form_fields", "parenttype": "CETI Form", "idx": 3, "fieldname": "credit_limits",
         "fieldtype": "Table", "label": "Credit Limit", "allow_read_on_all_link_options": 0, "reqd": 0,
         "depends_on": None, "read_only": 0, "show_in_filter": 0, "hidden": 0, "options": "Customer Credit Limit",
         "max_length": 0, "max_value": 0, "description": None, "default": "0"},
        {"name": "\"b2b23b396e\"", "creation": "2020-07-26 02:20:21.914657", "modified": "2020-07-26 02:20:21.914657",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0, "parent": "restaurant-room",
         "parentfield": "ceti_form_fields", "parenttype": "CETI Form", "idx": 3, "fieldname": "type",
         "fieldtype": "Select", "label": "Type", "allow_read_on_all_link_options": 0, "reqd": 1, "depends_on": None,
         "read_only": 0, "show_in_filter": 0, "hidden": 0,
         "options": "Room\nTable\nProduction Center\nTemporary Room\nDecorative", "max_length": 0, "max_value": 0,
         "description": None, "default": None},
        {"name": "\"b48b712ae4\"", "creation": "2020-07-26 02:20:21.576334", "modified": "2020-07-26 02:20:21.576334",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0, "parent": "payment-order",
         "parentfield": "ceti_form_fields", "parenttype": "CETI Form", "idx": 5, "fieldname": None, "fieldtype": "HTML",
         "label": "Payment Methods", "allow_read_on_all_link_options": 0, "reqd": 0, "depends_on": None, "read_only": 0,
         "show_in_filter": 0, "hidden": 0, "options": None, "max_length": 0, "max_value": 0, "description": None,
         "default": None},
        {"name": "\"bd67ef6b6a\"", "creation": "2020-07-26 02:20:22.006061", "modified": "2020-07-26 02:20:22.006061",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0, "parent": "restaurant-table",
         "parentfield": "ceti_form_fields", "parenttype": "CETI Form", "idx": 7, "fieldname": "minimum_seating",
         "fieldtype": "Int", "label": "Minimum Seating", "allow_read_on_all_link_options": 0, "reqd": 1,
         "depends_on": None, "read_only": 0, "show_in_filter": 0, "hidden": 0, "options": None, "max_length": 0,
         "max_value": 0, "description": None, "default": "1"},
        {"name": "\"c024414ff7\"", "creation": "2020-07-26 02:20:21.914657", "modified": "2020-07-26 02:20:21.914657",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0, "parent": "restaurant-room",
         "parentfield": "ceti_form_fields", "parenttype": "CETI Form", "idx": 5, "fieldname": "description",
         "fieldtype": "Data", "label": "Description", "allow_read_on_all_link_options": 0, "reqd": 0,
         "depends_on": None, "read_only": 0, "show_in_filter": 0, "hidden": 0, "options": None, "max_length": 0,
         "max_value": 0, "description": None, "default": None},
        {"name": "\"c66674ad38\"", "creation": "2020-07-26 02:20:21.914657", "modified": "2020-07-26 02:20:21.914657",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0, "parent": "restaurant-room",
         "parentfield": "ceti_form_fields", "parenttype": "CETI Form", "idx": 2, "fieldname": None,
         "fieldtype": "Section Break", "label": None, "allow_read_on_all_link_options": 0, "reqd": 0,
         "depends_on": None, "read_only": 0, "show_in_filter": 0, "hidden": 0, "options": None, "max_length": 0,
         "max_value": 0, "description": None, "default": None},
        {"name": "\"ca190f61fb\"", "creation": "2020-07-26 02:20:21.576334", "modified": "2020-07-26 02:20:21.576334",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0, "parent": "payment-order",
         "parentfield": "ceti_form_fields", "parenttype": "CETI Form", "idx": 14, "fieldname": None,
         "fieldtype": "Column Break", "label": None, "allow_read_on_all_link_options": 0, "reqd": 0, "depends_on": None,
         "read_only": 0, "show_in_filter": 0, "hidden": 0, "options": None, "max_length": 0, "max_value": 0,
         "description": None, "default": None},
        {"name": "\"cf0c848a33\"", "creation": "2020-07-26 02:20:22.006061", "modified": "2020-07-26 02:20:22.006061",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0, "parent": "restaurant-table",
         "parentfield": "ceti_form_fields", "parenttype": "CETI Form", "idx": 9, "fieldname": "description",
         "fieldtype": "Data", "label": "Description", "allow_read_on_all_link_options": 0, "reqd": 0,
         "depends_on": None, "read_only": 0, "show_in_filter": 0, "hidden": 0, "options": None, "max_length": 0,
         "max_value": 0, "description": None, "default": None},
        {"name": "\"d00aedf95c\"", "creation": "2020-07-26 02:20:22.059834", "modified": "2020-07-26 02:20:22.059834",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0,
         "parent": "restaurant-production-center", "parentfield": "ceti_form_fields", "parenttype": "CETI Form",
         "idx": 4, "fieldname": "section_break_2", "fieldtype": "Section Break", "label": None,
         "allow_read_on_all_link_options": 0, "reqd": 0, "depends_on": None, "read_only": 0, "show_in_filter": 0,
         "hidden": 0, "options": None, "max_length": 0, "max_value": 0, "description": None, "default": None},
        {"name": "\"d056ae6b28\"", "creation": "2020-07-26 02:20:22.059834", "modified": "2020-07-26 02:20:22.059834",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0,
         "parent": "restaurant-production-center", "parentfield": "ceti_form_fields", "parenttype": "CETI Form",
         "idx": 9, "fieldname": "status_managed", "fieldtype": "Table", "label": "Status Managed",
         "allow_read_on_all_link_options": 0, "reqd": 0, "depends_on": None, "read_only": 0, "show_in_filter": 0,
         "hidden": 0, "options": "Status Managed Production Center", "max_length": 0, "max_value": 0,
         "description": None, "default": None},
        {"name": "\"d74db69328\"", "creation": "2020-07-26 02:20:22.115430", "modified": "2020-07-26 02:20:22.115430",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0, "parent": "restaurant-order",
         "parentfield": "ceti_form_fields", "parenttype": "CETI Form", "idx": 1, "fieldname": "customer",
         "fieldtype": "Link", "label": "Customer", "allow_read_on_all_link_options": 0, "reqd": 0, "depends_on": None,
         "read_only": 0, "show_in_filter": 0, "hidden": 0, "options": "Customer", "max_length": 0, "max_value": 0,
         "description": None, "default": None},
        {"name": "\"de3749484e\"", "creation": "2020-07-26 02:20:21.576334", "modified": "2020-07-26 02:20:21.576334",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0, "parent": "payment-order",
         "parentfield": "ceti_form_fields", "parenttype": "CETI Form", "idx": 10, "fieldname": None,
         "fieldtype": "Column Break", "label": None, "allow_read_on_all_link_options": 0, "reqd": 0, "depends_on": None,
         "read_only": 0, "show_in_filter": 0, "hidden": 0, "options": None, "max_length": 0, "max_value": 0,
         "description": None, "default": None},
        {"name": "\"df042f17d2\"", "creation": "2020-07-26 02:20:22.059834", "modified": "2020-07-26 02:20:22.059834",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0,
         "parent": "restaurant-production-center", "parentfield": "ceti_form_fields", "parenttype": "CETI Form",
         "idx": 7, "fieldname": "color", "fieldtype": "Color", "label": "Color", "allow_read_on_all_link_options": 0,
         "reqd": 0, "depends_on": None, "read_only": 0, "show_in_filter": 0, "hidden": 0, "options": None,
         "max_length": 0, "max_value": 0, "description": None, "default": None},
        {"name": "\"fa67198cf4\"", "creation": "2020-07-26 02:20:21.914657", "modified": "2020-07-26 02:20:21.914657",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0, "parent": "restaurant-room",
         "parentfield": "ceti_form_fields", "parenttype": "CETI Form", "idx": 4, "fieldname": None,
         "fieldtype": "Column Break", "label": None, "allow_read_on_all_link_options": 0, "reqd": 0, "depends_on": None,
         "read_only": 0, "show_in_filter": 0, "hidden": 0, "options": None, "max_length": 0, "max_value": 0,
         "description": None, "default": None},
        {"name": "\"fbb8484e19\"", "creation": "2020-07-26 02:20:22.006061", "modified": "2020-07-26 02:20:22.006061",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0, "parent": "restaurant-table",
         "parentfield": "ceti_form_fields", "parenttype": "CETI Form", "idx": 1, "fieldname": "type",
         "fieldtype": "Select", "label": "Type", "allow_read_on_all_link_options": 0, "reqd": 1, "depends_on": None,
         "read_only": 0, "show_in_filter": 0, "hidden": 0,
         "options": "Room\nTable\nProduction Center\nTemporary Room\nDecorative", "max_length": 0, "max_value": 0,
         "description": None, "default": None},
        {"name": "\"ff9061396e\"", "creation": "2020-07-26 02:20:22.059834", "modified": "2020-07-26 02:20:22.059834",
         "modified_by": "Administrator", "owner": "Administrator", "docstatus": 0,
         "parent": "restaurant-production-center", "parentfield": "ceti_form_fields", "parenttype": "CETI Form",
         "idx": 11, "fieldname": "production_center_group", "fieldtype": "Table", "label": "Item Group",
         "allow_read_on_all_link_options": 0, "reqd": 0, "depends_on": None, "read_only": 0, "show_in_filter": 0,
         "hidden": 0, "options": "Production Center Group", "max_length": 0, "max_value": 0, "description": None,
         "default": None}
    ]

    for doc in docs:
        cf = frappe.get_doc("CETI Form", {
            "route": doc
        })
        cf.ceti_form_fields = []
        for f in fields:
            field = f
            if field["parent"] == doc:
                cf.append("ceti_form_fields", dict(
                    idx=field["idx"],
                    fieldname=field["fieldname"],
                    fieldtype=field["fieldtype"],
                    label=field["label"],
                    allow_read_on_all_link_options=1,
                    reqd=field["reqd"],
                    depends_on=field["depends_on"],
                    read_only=field["read_only"],
                    hidden=field["hidden"],
                    options=field["options"],
                    description=field["description"],
                    default=field["default"]
                ))

        cf.save()
